// Norsk A1/A2 — Vocabulario (NO ↔ ES) · Kapittel 1–13
// Nouns always include gender article (en / ei / et).
// Used by: vocab trainer mode + dynamically-generated write questions in exams.

window.VOCAB = [
  // ─── KAPITTEL 1 · Hva heter du? ──────────────────────────────────────────
  { topic: 1, no: 'å hete',           es: 'llamarse',              type: 'verb'  },
  { topic: 1, no: 'å komme fra',      es: 'ser de (origen)',        type: 'verb'  },
  { topic: 1, no: 'å bo',             es: 'vivir / residir',        type: 'verb'  },
  { topic: 1, no: 'å snakke',         es: 'hablar',                 type: 'verb'  },
  { topic: 1, no: 'et språk',         es: 'un idioma / una lengua', type: 'noun'  },
  { topic: 1, no: 'et land',          es: 'un país',                type: 'noun'  },
  { topic: 1, no: 'norsk',            es: 'noruego',                type: 'adj'   },
  { topic: 1, no: 'engelsk',          es: 'inglés',                 type: 'adj'   },
  { topic: 1, no: 'spansk',           es: 'español',                type: 'adj'   },
  { topic: 1, no: 'hva',              es: 'qué',                    type: 'phrase'},
  { topic: 1, no: 'hvor',             es: 'dónde',                  type: 'phrase'},
  { topic: 1, no: 'hvem',             es: 'quién',                  type: 'phrase'},
  { topic: 1, no: 'unnskyld',         es: 'perdona / disculpa',     type: 'phrase'},
  { topic: 1, no: 'ja',               es: 'sí',                     type: 'phrase'},
  { topic: 1, no: 'nei',              es: 'no',                     type: 'phrase'},
  { topic: 1, no: 'hei',              es: 'hola',                   type: 'phrase'},
  { topic: 1, no: 'ha det',           es: 'adiós / hasta luego',    type: 'phrase'},
  { topic: 1, no: 'hyggelig å treffe deg', es: 'encantado/a de conocerte', type: 'phrase'},

  // ─── KAPITTEL 2 · Hva gjør du? ────────────────────────────────────────────
  { topic: 2, no: 'å gjøre',          es: 'hacer',                  type: 'verb'  },
  { topic: 2, no: 'å vaske',          es: 'lavar',                  type: 'verb'  },
  { topic: 2, no: 'å lage mat',       es: 'cocinar / preparar comida', type: 'verb'},
  { topic: 2, no: 'å lese',           es: 'leer',                   type: 'verb'  },
  { topic: 2, no: 'å spise',          es: 'comer',                  type: 'verb'  },
  { topic: 2, no: 'å se på TV',       es: 'ver la televisión',      type: 'verb'  },
  { topic: 2, no: 'en lærer',         es: 'un/a profesor/a',        type: 'noun'  },
  { topic: 2, no: 'en servitør',      es: 'un/a camarero/a',        type: 'noun'  },
  { topic: 2, no: 'en kokk',          es: 'un/a cocinero/a',        type: 'noun'  },
  { topic: 2, no: 'en journalist',    es: 'un/a periodista',        type: 'noun'  },
  { topic: 2, no: 'en resepsjonist',  es: 'un/a recepcionista',     type: 'noun'  },
  { topic: 2, no: 'mandag',           es: 'lunes',                  type: 'noun'  },
  { topic: 2, no: 'tirsdag',          es: 'martes',                 type: 'noun'  },
  { topic: 2, no: 'onsdag',           es: 'miércoles',              type: 'noun'  },
  { topic: 2, no: 'torsdag',          es: 'jueves',                 type: 'noun'  },
  { topic: 2, no: 'fredag',           es: 'viernes',                type: 'noun'  },
  { topic: 2, no: 'lørdag',           es: 'sábado',                 type: 'noun'  },
  { topic: 2, no: 'søndag',           es: 'domingo',                type: 'noun'  },
  { topic: 2, no: 'en frokost',       es: 'un desayuno',            type: 'noun'  },
  { topic: 2, no: 'en kaffe',         es: 'un café',                type: 'noun'  },

  // ─── KAPITTEL 3 · Fra morgen til kveld ────────────────────────────────────
  { topic: 3, no: 'et vekkerur',      es: 'un despertador',         type: 'noun'  },
  { topic: 3, no: 'å stå opp',        es: 'levantarse',             type: 'verb'  },
  { topic: 3, no: 'om morgenen',      es: 'por la mañana',          type: 'phrase'},
  { topic: 3, no: 'om kvelden',       es: 'por la tarde/noche',     type: 'phrase'},
  { topic: 3, no: 'ei klokke',        es: 'un reloj',               type: 'noun'  },
  { topic: 3, no: 'kvart over',       es: 'y cuarto',               type: 'phrase'},
  { topic: 3, no: 'kvart på',         es: 'menos cuarto',           type: 'phrase'},
  { topic: 3, no: 'halv',             es: 'y media (menos 30 min)', type: 'phrase'},
  { topic: 3, no: 'en dusj',          es: 'una ducha',              type: 'noun'  },
  { topic: 3, no: 'et brød',          es: 'un pan',                 type: 'noun'  },
  { topic: 3, no: 'ei skive',         es: 'una rebanada',           type: 'noun'  },
  { topic: 3, no: 'et glass',         es: 'un vaso',                type: 'noun'  },
  { topic: 3, no: 'å sove',           es: 'dormir',                 type: 'verb'  },
  { topic: 3, no: 'å legge seg',      es: 'acostarse',              type: 'verb'  },
  { topic: 3, no: 'vanligvis',        es: 'normalmente / por lo general', type: 'adv'},

  // ─── KAPITTEL 4 · På norskkurs ────────────────────────────────────────────
  { topic: 4, no: 'et ord',           es: 'una palabra',            type: 'noun'  },
  { topic: 4, no: 'å forstå',         es: 'entender / comprender',  type: 'verb'  },
  { topic: 4, no: 'å gjenta',         es: 'repetir',                type: 'verb'  },
  { topic: 4, no: 'å spørre',         es: 'preguntar',              type: 'verb'  },
  { topic: 4, no: 'å svare',          es: 'responder / contestar',  type: 'verb'  },
  { topic: 4, no: 'en gang til',      es: 'otra vez / de nuevo',    type: 'phrase'},
  { topic: 4, no: 'å undervise',      es: 'enseñar / dar clase',    type: 'verb'  },
  { topic: 4, no: 'muntlig',          es: 'oral / de forma oral',   type: 'adj'   },
  { topic: 4, no: 'skriftlig',        es: 'escrito / por escrito',  type: 'adj'   },
  { topic: 4, no: 'å lære',           es: 'aprender',               type: 'verb'  },
  { topic: 4, no: 'et svar',          es: 'una respuesta',          type: 'noun'  },
  { topic: 4, no: 'å prøve',          es: 'intentar / probar',      type: 'verb'  },
  { topic: 4, no: 'vanskelig',        es: 'difícil',                type: 'adj'   },
  { topic: 4, no: 'lett',             es: 'fácil',                  type: 'adj'   },

  // ─── KAPITTEL 5 · Familieliv ──────────────────────────────────────────────
  { topic: 5, no: 'en far',           es: 'un padre',               type: 'noun'  },
  { topic: 5, no: 'ei mor',           es: 'una madre',              type: 'noun'  },
  { topic: 5, no: 'en sønn',          es: 'un hijo',                type: 'noun'  },
  { topic: 5, no: 'ei datter',        es: 'una hija',               type: 'noun'  },
  { topic: 5, no: 'en bror',          es: 'un hermano',             type: 'noun'  },
  { topic: 5, no: 'ei søster',        es: 'una hermana',            type: 'noun'  },
  { topic: 5, no: 'en hund',          es: 'un perro',               type: 'noun'  },
  { topic: 5, no: 'ei katt',          es: 'una gata / un gato',     type: 'noun'  },
  { topic: 5, no: 'et barn',          es: 'un niño / un hijo',      type: 'noun'  },
  { topic: 5, no: 'en mann',          es: 'un hombre / un marido',  type: 'noun'  },
  { topic: 5, no: 'ei dame',          es: 'una señora / una dama',  type: 'noun'  },
  { topic: 5, no: 'en bestemor',      es: 'una abuela',             type: 'noun'  },
  { topic: 5, no: 'en bestefar',      es: 'un abuelo',              type: 'noun'  },
  { topic: 5, no: 'en barnehage',     es: 'una guardería / jardín de infancia', type: 'noun'},
  { topic: 5, no: 'mat',              es: 'comida',                 type: 'noun'  },
  { topic: 5, no: 'sulten',           es: 'hambriento/a',           type: 'adj'   },
  { topic: 5, no: 'mett',             es: 'lleno/a (de comida)',     type: 'adj'   },

  // ─── KAPITTEL 6 · På kjøpesenteret ───────────────────────────────────────
  { topic: 6, no: 'en bukse',         es: 'unos pantalones',        type: 'noun'  },
  { topic: 6, no: 'en kjole',         es: 'un vestido',             type: 'noun'  },
  { topic: 6, no: 'en jakke',         es: 'una chaqueta',           type: 'noun'  },
  { topic: 6, no: 'en skjorte',       es: 'una camisa',             type: 'noun'  },
  { topic: 6, no: 'et skjørt',        es: 'una falda',              type: 'noun'  },
  { topic: 6, no: 'en genser',        es: 'un jersey / un suéter',  type: 'noun'  },
  { topic: 6, no: 'en frakk',         es: 'un abrigo',              type: 'noun'  },
  { topic: 6, no: 'et slips',         es: 'una corbata',            type: 'noun'  },
  { topic: 6, no: 'en sko',           es: 'un zapato',              type: 'noun'  },
  { topic: 6, no: 'en sokk',          es: 'un calcetín',            type: 'noun'  },
  { topic: 6, no: 'en lue',           es: 'un gorro',               type: 'noun'  },
  { topic: 6, no: 'billig',           es: 'barato/a',               type: 'adj'   },
  { topic: 6, no: 'dyr',              es: 'caro/a',                 type: 'adj'   },
  { topic: 6, no: 'stor',             es: 'grande',                 type: 'adj'   },
  { topic: 6, no: 'liten',            es: 'pequeño/a',              type: 'adj'   },
  { topic: 6, no: 'en kasse',         es: 'una caja registradora',  type: 'noun'  },
  { topic: 6, no: 'en rabatt',        es: 'un descuento',           type: 'noun'  },

  // ─── KAPITTEL 7 · Her bor jeg ────────────────────────────────────────────
  { topic: 7, no: 'ei leilighet',     es: 'un piso / un apartamento', type: 'noun'},
  { topic: 7, no: 'en enebolig',      es: 'una casa unifamiliar',   type: 'noun'  },
  { topic: 7, no: 'et rekkehus',      es: 'una casa adosada',       type: 'noun'  },
  { topic: 7, no: 'ei hytte',         es: 'una cabaña',             type: 'noun'  },
  { topic: 7, no: 'en blokk',         es: 'un bloque de pisos',     type: 'noun'  },
  { topic: 7, no: 'å leie',           es: 'alquilar',               type: 'verb'  },
  { topic: 7, no: 'å eie',            es: 'poseer / ser propietario', type: 'verb'},
  { topic: 7, no: 'ei husleie',       es: 'un alquiler',            type: 'noun'  },
  { topic: 7, no: 'et boliglån',      es: 'una hipoteca',           type: 'noun'  },
  { topic: 7, no: 'en etasje',        es: 'una planta / un piso',   type: 'noun'  },
  { topic: 7, no: 'et kjøkken',       es: 'una cocina',             type: 'noun'  },
  { topic: 7, no: 'en stue',          es: 'un salón / una sala de estar', type: 'noun'},
  { topic: 7, no: 'et soverom',       es: 'una habitación / un dormitorio', type: 'noun'},
  { topic: 7, no: 'et bad',           es: 'un baño',                type: 'noun'  },
  { topic: 7, no: 'en hage',          es: 'un jardín',              type: 'noun'  },
  { topic: 7, no: 'å flytte',         es: 'mudarse',                type: 'verb'  },
  { topic: 7, no: 'i byen',           es: 'en la ciudad',           type: 'phrase'},
  { topic: 7, no: 'på landet',        es: 'en el campo',            type: 'phrase'},
  { topic: 7, no: 'ved sjøen',        es: 'junto al mar',           type: 'phrase'},

  // ─── KAPITTEL 8 · Prøv i pausen (Jobb / CV) ──────────────────────────────
  { topic: 8, no: 'et arbeid',        es: 'un trabajo',             type: 'noun'  },
  { topic: 8, no: 'en jobb',          es: 'un trabajo',             type: 'noun'  },
  { topic: 8, no: 'en lønn',          es: 'un salario / un sueldo', type: 'noun'  },
  { topic: 8, no: 'en ansatt',        es: 'un/a empleado/a',        type: 'noun'  },
  { topic: 8, no: 'en sjef',          es: 'un/a jefe/a',            type: 'noun'  },
  { topic: 8, no: 'et møte',          es: 'una reunión',            type: 'noun'  },
  { topic: 8, no: 'å spare',          es: 'ahorrar',                type: 'verb'  },
  { topic: 8, no: 'en erfaring',      es: 'una experiencia',        type: 'noun'  },
  { topic: 8, no: 'å søke jobb',      es: 'buscar trabajo',         type: 'verb'  },
  { topic: 8, no: 'en CV',            es: 'un currículum',          type: 'noun'  },
  { topic: 8, no: 'stressende',       es: 'estresante',             type: 'adj'   },
  { topic: 8, no: 'en bank',          es: 'un banco',               type: 'noun'  },

  // ─── KAPITTEL 9 · Vær og årstider ────────────────────────────────────────
  { topic: 9, no: 'et vær',           es: 'el tiempo (meteorológico)', type: 'noun'},
  { topic: 9, no: 'en årstid',        es: 'una estación del año',   type: 'noun'  },
  { topic: 9, no: 'en vår',           es: 'la primavera',           type: 'noun'  },
  { topic: 9, no: 'en sommer',        es: 'verano',                 type: 'noun'  },
  { topic: 9, no: 'en høst',          es: 'el otoño',               type: 'noun'  },
  { topic: 9, no: 'en vinter',        es: 'el invierno',            type: 'noun'  },
  { topic: 9, no: 'sol',              es: 'sol',                    type: 'noun'  },
  { topic: 9, no: 'regn',             es: 'lluvia',                 type: 'noun'  },
  { topic: 9, no: 'snø',              es: 'nieve',                  type: 'noun'  },
  { topic: 9, no: 'vind',             es: 'viento',                 type: 'noun'  },
  { topic: 9, no: 'et uvær',          es: 'una tormenta',           type: 'noun'  },
  { topic: 9, no: 'en sky',           es: 'una nube',               type: 'noun'  },
  { topic: 9, no: 'kald',             es: 'frío/a',                 type: 'adj'   },
  { topic: 9, no: 'varm',             es: 'caliente / cálido/a',    type: 'adj'   },
  { topic: 9, no: 'å skinne',         es: 'brillar (el sol)',        type: 'verb'  },
  { topic: 9, no: 'tåke',             es: 'niebla',                 type: 'noun'  },
  { topic: 9, no: 'glatt',            es: 'resbaladizo/a',          type: 'adj'   },

  // ─── KAPITTEL 10 · Litt om Norge ─────────────────────────────────────────
  { topic: 10, no: 'en hval',         es: 'una ballena',            type: 'noun'  },
  { topic: 10, no: 'en fjord',        es: 'un fiordo',              type: 'noun'  },
  { topic: 10, no: 'en midnattssol',  es: 'el sol de medianoche',   type: 'noun'  },
  { topic: 10, no: 'nordlys',         es: 'aurora boreal',          type: 'noun'  },
  { topic: 10, no: 'et fjell',        es: 'una montaña',            type: 'noun'  },
  { topic: 10, no: 'en strand',       es: 'una playa',              type: 'noun'  },
  { topic: 10, no: 'en ø',            es: 'una isla',               type: 'noun'  },
  { topic: 10, no: 'en sjø',          es: 'un lago',                type: 'noun'  },
  { topic: 10, no: 'en elv',          es: 'un río',                 type: 'noun'  },
  { topic: 10, no: 'en bre',          es: 'un glaciar',             type: 'noun'  },
  { topic: 10, no: 'et grantre',      es: 'un abeto',               type: 'noun'  },
  { topic: 10, no: 'et bjørketre',    es: 'un abedul',              type: 'noun'  },
  { topic: 10, no: 'en bro',          es: 'un puente',              type: 'noun'  },
  { topic: 10, no: 'et skip',         es: 'un barco / un buque',    type: 'noun'  },
  { topic: 10, no: 'en lastebil',     es: 'un camión',              type: 'noun'  },
  { topic: 10, no: 'en sykkel',       es: 'una bicicleta',          type: 'noun'  },
  { topic: 10, no: 'et fly',          es: 'un avión',               type: 'noun'  },
  { topic: 10, no: 'en brygge',       es: 'un muelle / un embarcadero', type: 'noun'},
  { topic: 10, no: 'en turist',       es: 'un/a turista',           type: 'noun'  },
  { topic: 10, no: 'utenlandsk',      es: 'extranjero/a',           type: 'adj'   },
  { topic: 10, no: 'fantastisk',      es: 'fantástico/a',           type: 'adj'   },
  { topic: 10, no: 'strålende',       es: 'radiante / espléndido/a', type: 'adj'  },
  { topic: 10, no: 'en natur',        es: 'la naturaleza',          type: 'noun'  },
  { topic: 10, no: 'en fisker',       es: 'un/a pescador/a',        type: 'noun'  },
  { topic: 10, no: 'et landskap',     es: 'un paisaje',             type: 'noun'  },

  // ─── KAPITTEL 11 · Språkpraksis ──────────────────────────────────────────
  { topic: 11, no: 'en mekaniker',    es: 'un/a mecánico/a',        type: 'noun'  },
  { topic: 11, no: 'et verksted',     es: 'un taller (mecánico)',   type: 'noun'  },
  { topic: 11, no: 'en sykepleier',   es: 'un/a enfermero/a',       type: 'noun'  },
  { topic: 11, no: 'et sykehjem',     es: 'una residencia de ancianos', type: 'noun'},
  { topic: 11, no: 'en bartender',    es: 'un/a barman / camarero/a de barra', type: 'noun'},
  { topic: 11, no: 'en parkeringsvakt', es: 'un/a vigilante de aparcamiento', type: 'noun'},
  { topic: 11, no: 'elektronikk',     es: 'electrónica',            type: 'noun'  },
  { topic: 11, no: 'moderne',         es: 'moderno/a',              type: 'adj'   },
  { topic: 11, no: 'interessert',     es: 'interesado/a',           type: 'adj'   },
  { topic: 11, no: 'alene',           es: 'solo/a',                 type: 'adv'   },
  { topic: 11, no: 'ensom',           es: 'solitario/a / solo/a',   type: 'adj'   },
  { topic: 11, no: 'bekymret',        es: 'preocupado/a',           type: 'adj'   },
  { topic: 11, no: 'en flyktning',    es: 'un/a refugiado/a',       type: 'noun'  },
  { topic: 11, no: 'et asylmottak',   es: 'un centro de acogida de refugiados', type: 'noun'},
  { topic: 11, no: 'deprimert',       es: 'deprimido/a',            type: 'adj'   },
  { topic: 11, no: 'å konsentrere seg', es: 'concentrarse',         type: 'verb'  },
  { topic: 11, no: 'et kontor',       es: 'una oficina',            type: 'noun'  },
  { topic: 11, no: 'et ansvar',       es: 'una responsabilidad',    type: 'noun'  },
  { topic: 11, no: 'en leder',        es: 'un/a líder / jefe/a',    type: 'noun'  },
  { topic: 11, no: 'mineralvann',     es: 'agua mineral',           type: 'noun'  },
  { topic: 11, no: 'dialekt',         es: 'dialecto',               type: 'noun'  },
  { topic: 11, no: 'alkohol',         es: 'alcohol',                type: 'noun'  },

  // ─── KAPITTEL 12 · Livsstil, kropp og helse ──────────────────────────────
  { topic: 12, no: 'en kropp',        es: 'un cuerpo',              type: 'noun'  },
  { topic: 12, no: 'et kosthold',     es: 'una dieta / alimentación', type: 'noun'},
  { topic: 12, no: 'en helse',        es: 'la salud',               type: 'noun'  },
  { topic: 12, no: 'et hode',         es: 'una cabeza',             type: 'noun'  },
  { topic: 12, no: 'en arm',          es: 'un brazo',               type: 'noun'  },
  { topic: 12, no: 'et bein',         es: 'una pierna',             type: 'noun'  },
  { topic: 12, no: 'en fot',          es: 'un pie',                 type: 'noun'  },
  { topic: 12, no: 'en hånd',         es: 'una mano',               type: 'noun'  },
  { topic: 12, no: 'et øye',          es: 'un ojo',                 type: 'noun'  },
  { topic: 12, no: 'et øre',          es: 'una oreja',              type: 'noun'  },
  { topic: 12, no: 'en nese',         es: 'una nariz',              type: 'noun'  },
  { topic: 12, no: 'en munn',         es: 'una boca',               type: 'noun'  },
  { topic: 12, no: 'en rygg',         es: 'una espalda',            type: 'noun'  },
  { topic: 12, no: 'en mage',         es: 'un estómago / una barriga', type: 'noun'},
  { topic: 12, no: 'en lege',         es: 'un/a médico/a',          type: 'noun'  },
  { topic: 12, no: 'et sykehus',      es: 'un hospital',            type: 'noun'  },
  { topic: 12, no: 'en medisin',      es: 'un medicamento',         type: 'noun'  },
  { topic: 12, no: 'smertestillende', es: 'analgésico / calmante',  type: 'adj'   },
  { topic: 12, no: 'å trene',         es: 'entrenar / hacer deporte', type: 'verb'},
  { topic: 12, no: 'sunn',            es: 'sano/a',                 type: 'adj'   },
  { topic: 12, no: 'usunn',           es: 'malsano/a',              type: 'adj'   },
  { topic: 12, no: 'trøtt',           es: 'cansado/a',              type: 'adj'   },
  { topic: 12, no: 'syk',             es: 'enfermo/a',              type: 'adj'   },
  { topic: 12, no: 'et brudd',        es: 'una fractura',           type: 'noun'  },
  { topic: 12, no: 'en fysioterapeut',es: 'un/a fisioterapeuta',    type: 'noun'  },

  // ─── KAPITTEL 13 · På hotellet ───────────────────────────────────────────
  { topic: 13, no: 'et hotell',       es: 'un hotel',               type: 'noun'  },
  { topic: 13, no: 'et rom',          es: 'una habitación',         type: 'noun'  },
  { topic: 13, no: 'en resepsjon',    es: 'una recepción',          type: 'noun'  },
  { topic: 13, no: 'en nøkkel',       es: 'una llave',              type: 'noun'  },
  { topic: 13, no: 'å sjekke inn',    es: 'hacer el check-in',      type: 'verb'  },
  { topic: 13, no: 'å sjekke ut',     es: 'hacer el check-out',     type: 'verb'  },
  { topic: 13, no: 'en seng',         es: 'una cama',               type: 'noun'  },
  { topic: 13, no: 'et teppe',        es: 'una manta / una alfombra', type: 'noun'},
  { topic: 13, no: 'en pute',         es: 'una almohada',           type: 'noun'  },
  { topic: 13, no: 'å reservere',     es: 'reservar',               type: 'verb'  },
  { topic: 13, no: 'ledig',           es: 'libre / disponible',     type: 'adj'   },
  { topic: 13, no: 'opptatt',         es: 'ocupado/a',              type: 'adj'   },
  { topic: 13, no: 'en bagasje',      es: 'equipaje',               type: 'noun'  },
  { topic: 13, no: 'en opplevelse',   es: 'una experiencia / vivencia', type: 'noun'},
  { topic: 13, no: 'en tradisjon',    es: 'una tradición',          type: 'noun'  },
  { topic: 13, no: 'en guide',        es: 'un/a guía turístico/a',  type: 'noun'  },
  { topic: 13, no: 'en sightseeingtur', es: 'una visita turística', type: 'noun'  },
  { topic: 13, no: 'stille',          es: 'silencioso/a / tranquilo/a', type: 'adj'},
  { topic: 13, no: 'en tur',          es: 'un viaje / una excursión', type: 'noun'},
];
